@SerilogTest_HostAddress = https://localhost:7119

GET {{SerilogTest_HostAddress}}/LogTest/LogWarning/
Accept: application/json

###

GET {{SerilogTest_HostAddress}}/LogTest/LogError/
Accept: application/json

###

GET {{SerilogTest_HostAddress}}/LogTest/LogErrorThrow/
Accept: application/json

###
