name: Test & Coverage

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: 6.0.x, 5.0.x
      - name: Restore dependencies
        working-directory: ./src
        run: dotnet restore
      - name: Build
        working-directory: ./src
        run: dotnet build --no-restore /p:ContinuousIntegrationBuild=true
      - name: Test
        working-directory: ./src
        run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
      - name: Codecov
        uses: codecov/codecov-action@v2.0.2
